extends: stylelint-config-recommended

rules:
  selector-pseudo-class-no-unknown:
    - true
    - ignorePseudoClasses:
        - component
        - external
        - global

  property-no-unknown:
    - true
    - ignoreProperties:
        - composes

  selector-type-no-unknown: null

  selector-class-pattern:
    - '^[a-z][a-zA-Z0-9]+$'

  custom-property-pattern: '^[a-z][a-zA-Z0-9]+$'
